# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'Midas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Architecture
  pod 'ReactorKit'

  # Networking
  pod 'Alamofire', '~> 4.4.0'
  pod 'Moya', '~> 10.0.0-beta.1'
  pod 'Moya/RxSwift'
#  pod 'Kingfisher', '~> 4.6.1'
  pod 'PINRemoteImage', '~> 3.0.0-beta.13'
  
  # Model
  
  # UI.
  pod 'SnapKit', '~> 4.0.0'
  pod 'ReusableKit', '~> 2.0.1'
  pod 'ManualLayout'
  
  # Rx
  pod 'RxSwift', '~> 4.0.0'
  pod 'RxOptional', '~> 3.3.0'
  pod 'RxViewController'
  
  # Misc
  pod 'Then', '~> 2.3.0'
  pod 'SwiftSoup', '~> 1.5.8'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'SwiftyColor', '~> 1.0.0'
  pod 'SwiftyImage', '~> 1.2.0'

  target 'MidasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
