# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'Midas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Midas
  pod 'Alamofire', '~> 4.4.0'
  pod 'SwiftSoup', '~> 1.5.8'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'RxSwift', '~> 4.0.0'

  target 'MidasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
